[package]
name = "substrate-api-client"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
env_logger      = { version = "0.7", optional = true }
ws              = { version = "0.7", optional = true }
hex             = { version = "0.4", default-features = false }
log             = { version = "0.4", optional = true }
serde           = { version = "1.0", optional = true, features = ["derive"] }
serde_json      = { version = "1.0", optional = true }
thiserror = "1.0"
primitive-types = { version = "0.6.1", default-features = false, features = ["codec"] }

[dependencies.sp-core]
version = '2.0.0-alpha.5'
package = "sp-core"
default-features = false
features = ["full_crypto"]

[dependencies.codec]
package = "parity-scale-codec"
features = ["derive"]
version = "1.3.0"
default-features = false

#[dependencies.indices]
#version = '2.0.0-alpha.5'
#package = "pallet-indices"
#default-features=false

[dependencies.runtime_io]
version = '2.0.0-alpha.5'
package = "sp-io"
default-features=false

[dependencies.metadata]
version = '11.0.0-alpha.5'
package = "frame-metadata"
default-features=false

[dependencies.sp-version]
version = '2.0.0-alpha.5'
package = "sp-version"
default-features=false

[dependencies.balances]
version = '2.0.0-alpha.5'
package = "pallet-balances"
default-features=false

[dependencies.system]
version = '2.0.0-alpha.5'
package = "frame-system"
default-features=false

[dependencies.sp-runtime]
version = '2.0.0-alpha.5'
package = "sp-runtime"
default-features=false

[dependencies.support]
version = '2.0.0-alpha.5'
package = "frame-support"
default-features=false

[dependencies.sp-std]
version = '2.0.0-alpha.5'
package = "sp-std"
default-features = false

[dependencies.node_template_runtime]
git = "https://github.com/scs/substrate-node-template"
branch = 'test-api-client'
package = "node-template-runtime"
default-features = false

[dev-dependencies.contracts]
version = '2.0.0-alpha.5'
package = "pallet-contracts"

[dev-dependencies]
wabt = "0.9.0"

[dependencies.keyring]
version = '2.0.0-alpha.5'
package = "sp-keyring"

[dev-dependencies.clap] 
version = "2.33"
features = ["yaml"] 

[dev-dependencies.test_node_runtime]
git = "https://github.com/scs/substrate-test-nodes"
tag = "api-M1.5"
package = "test-node-runtime"

[features]
default = ["std"]
std = [
	"sp-core/std",
	"codec/std",
    "sp-runtime/std",
	"support/std",
	"sp-runtime/std",
	"system/std",
	"balances/std",
	"sp-version/std",
	"metadata/std",
	"runtime_io/std",
#	"indices/std",
	"sp-core/std",
	"serde/std",
	"serde_json",
	"env_logger",
	"log",
	"ws",
	"hex/std",
	"primitive-types/std",
	"node_template_runtime/std",
]
# need to add this for the app_crypto macro
full_crypto = []

[[example]]
name = "example_get_storage"
path = "src/examples/example_get_storage.rs"

[[example]]
name = "example_get_blocks"
path = "src/examples/example_get_blocks.rs"

[[example]]
name = "example_transfer"
path = "src/examples/example_transfer.rs"

[[example]]
name = "example_event_callback"
path = "src/examples/example_event_callback.rs"

[[example]]
name = "example_generic_extrinsic"
path = "src/examples/example_generic_extrinsic.rs"

[[example]]
name = "example_print_metadata"
path = "src/examples/example_print_metadata.rs"

[[example]]
name = "example_contract"
path = "src/examples/example_contract.rs"

[[example]]
name = "example_custom_storage_struct"
path = "src/examples/example_custom_storage_struct.rs"

[[example]]
name = "example_compose_extrinsic_offline"
path = "src/examples/example_compose_extrinsic_offline.rs"

[[example]]
name = "example_generic_event_callback"
path = "src/examples/example_generic_event_callback.rs"

[[example]]
name = "example_benchmark_bulk_xt"
path = "src/examples/example_benchmark_bulk_xt.rs"

[[example]]
name = "example_sudo"
path = "src/examples/example_sudo.rs"
